import { Platform, StyleSheet } from "react-native";

/**
 *
 */
export const styles = StyleSheet.create({
  root: {},
  view: {},
  codeBlock: {
    color: "white",
    borderWidth: 1,
    borderColor: "#CCCCCC",
    backgroundColor: "#f5f5f5",
    padding: 10,
    borderRadius: 4,
  },
  codeInline: {
    color: "white",
    borderWidth: 1,
    borderColor: "#CCCCCC",
    backgroundColor: "#f5f5f5",
    padding: 10,
    borderRadius: 4,
  },
  del: { color: "white", backgroundColor: "#000000" },
  em: { color: "white", fontStyle: "italic" },
  headingContainer: { color: "white", flexDirection: "row" },
  heading: { color: "white" },
  heading1: { color: "white", fontSize: 32 },
  heading2: { color: "white", fontSize: 24 },
  heading3: { color: "white", fontSize: 18 },
  heading4: { color: "white", fontSize: 16 },
  heading5: { color: "white", fontSize: 13 },
  heading6: { color: "white", fontSize: 11 },
  hr: { color: "white", backgroundColor: "#000000", height: 1 },
  blockquote: {
    color: "white",
    paddingHorizontal: 20,
    paddingVertical: 10,
    margin: 20,
    backgroundColor: "#CCCCCC",
  },
  inlineCode: {
    color: "white",
    borderRadius: 3,
    borderWidth: 1,
    fontFamily: "Courier",
    fontWeight: "bold",
  },
  list: { color: "white" },
  listItem: {
    color: "white",
    flex: 1,
    flexWrap: "wrap",
    // backgroundColor: 'green',
  },
  listUnordered: { color: "white" },

  listUnorderedItem: {
    color: "white",
    flexDirection: "row",
    justifyContent: "flex-start",
  },

  listUnorderedItemIcon: {
    color: "white",
    marginLeft: 10,
    marginRight: 10,
    color: "white",
    lineHeight: 36,
  },
  listUnorderedItemText: { color: "white", fontSize: 20, lineHeight: 20 },

  listOrdered: { color: "white" },
  listOrderedItem: { color: "white", flexDirection: "row" },
  listOrderedItemIcon: {
    color: "white",
    marginLeft: 10,
    marginRight: 10,
    color: "white",
    lineHeight: 36,
  },
  listOrderedItemText: { color: "white", fontWeight: "bold", lineHeight: 20 },
  paragraph: {
    color: "white",
    marginTop: 10,
    marginBottom: 10,
    flexWrap: "wrap",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  hardbreak: { color: "white", width: "100%", height: 1 },
  strong: { color: "white", fontWeight: "bold" },
  table: {
    color: "white",
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 3,
  },
  tableHeader: { color: "white" },
  tableHeaderCell: {
    color: "white",
    flex: 1,
    // color: '#000000',
    padding: 5,
    // backgroundColor: 'green',
  },
  tableRow: {
    color: "white",
    borderBottomWidth: 1,
    borderColor: "#000000",
    flexDirection: "row",
  },
  tableRowCell: { color: "white", flex: 1, padding: 5 },
  text: { color: "white" },
  strikethrough: { color: "white", textDecorationLine: "line-through" },
  link: { color: "white", textDecorationLine: "underline" },
  blocklink: {
    color: "white",
    flex: 1,
    borderColor: "#000000",
    borderBottomWidth: 1,
  },
  u: { color: "white", borderColor: "#000000", borderBottomWidth: 1 },
  image: { color: "white" },
});
